export const products =
[{id: 0, nombre: "oráculo conexión con el universo box", descripcion: "La descripción iría acá, pero bueno, como voy bien atrasado con React le estoy dando más enfoque a aprender cosas nuevas por los momentos y no en añadirle descripciones a los productos xD", precioUnidad: 3990, stock: 5, img: "./images/productos/cartas/universobox.jpg"},
{id: 1, nombre: "oráculo conexión con el universo simple", descripcion: "La descripción iría acá, pero bueno, como voy bien atrasado con React le estoy dando más enfoque a aprender cosas nuevas por los momentos y no en añadirle descripciones a los productos xD", precioUnidad: 2650, stock: 35, img: "./images/productos/cartas/universosolo.jpg"},
{id: 2, nombre: "lectura de cartas 45min", descripcion: "La descripción iría acá, pero bueno, como voy bien atrasado con React le estoy dando más enfoque a aprender cosas nuevas por los momentos y no en añadirle descripciones a los productos xD", precioUnidad:4800, stock: Infinity, img: "./images/productos/tarot.jpg"},
{id: 3, nombre: "kit personal 7 chakras", descripcion: "La descripción iría acá, pero bueno, como voy bien atrasado con React le estoy dando más enfoque a aprender cosas nuevas por los momentos y no en añadirle descripciones a los productos xD", precioUnidad:2650, stock: 12, img: "./images/productos/limpieza/chakras.jpg"},
{id: 4, nombre: "spry limpieza energética sandalo y champa", descripcion: "La descripción iría acá, pero bueno, como voy bien atrasado con React le estoy dando más enfoque a aprender cosas nuevas por los momentos y no en añadirle descripciones a los productos xD", precioUnidad: 650, stock: 16, img: "./images/productos/limpieza/sandaloychampa.jpg"},
{id: 5, nombre: "spry limpieza energética de descarga", descripcion: "La descripción iría acá, pero bueno, como voy bien atrasado con React le estoy dando más enfoque a aprender cosas nuevas por los momentos y no en añadirle descripciones a los productos xD", precioUnidad: 650, stock: 11, img: "./images/productos/limpieza/limpieza.jpg"},
{id: 6, nombre: "spry limpieza energética ruda y romero", descripcion: "La descripción iría acá, pero bueno, como voy bien atrasado con React le estoy dando más enfoque a aprender cosas nuevas por los momentos y no en añadirle descripciones a los productos xD", precioUnidad: 690, stock: 19, img: "./images/productos/limpieza/rudayromero.jpg"},
{id: 7, nombre: "spry limpieza energética abundancia y fortuna", descripcion: "La descripción iría acá, pero bueno, como voy bien atrasado con React le estoy dando más enfoque a aprender cosas nuevas por los momentos y no en añadirle descripciones a los productos xD", precioUnidad: 780, stock: 25, img: "./images/productos/limpieza/abundanciayfortuna.jpg"},
{id: 8, nombre: "vela de soja de la abundancia y fortuna", descripcion: "La descripción iría acá, pero bueno, como voy bien atrasado con React le estoy dando más enfoque a aprender cosas nuevas por los momentos y no en añadirle descripciones a los productos xD", precioUnidad: 890, stock: 2, img: "./images/productos/velas/abundancia.jpg"},
{id: 9, nombre: "vela de soja del amor", descripcion: "La descripción iría acá, pero bueno, como voy bien atrasado con React le estoy dando más enfoque a aprender cosas nuevas por los momentos y no en añadirle descripciones a los productos xD", precioUnidad: 890, stock: 22, img: "./images/productos/velas/amor.jpg"},
{id: 10, nombre: 'vela de soja "buda"', descripcion: "La descripción iría acá, pero bueno, como voy bien atrasado con React le estoy dando más enfoque a aprender cosas nuevas por los momentos y no en añadirle descripciones a los productos xD", precioUnidad: 950, stock: 20, img: "./images/productos/velas/buda.jpg"},
{id: 11, nombre: "vela de soja de limpieza energética", descripcion: "La descripción iría acá, pero bueno, como voy bien atrasado con React le estoy dando más enfoque a aprender cosas nuevas por los momentos y no en añadirle descripciones a los productos xD", precioUnidad: 920, stock: 20, img: "./images/productos/velas/limpieza.jpg"},
{id: 12, nombre: "vela de soja de la seducción", descripcion: "La descripción iría acá, pero bueno, como voy bien atrasado con React le estoy dando más enfoque a aprender cosas nuevas por los momentos y no en añadirle descripciones a los productos xD", precioUnidad: 990, stock: 9, img: "./images/productos/velas/seduccion.jpg"}]